export const characters = [
    {
        id: 1,
        name: "Alex",
        image: "images/characters/alex.png",
        male: true,
        female: false,
        blackHair: true, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHAir: false,
        glasses: false,
        hat: false,
        mustache: true,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 2,
        name: "Alfred",
        image: "images/characters/alfred.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: true,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: true,
        beard: false,
        brownEyes: false,
        blueEyes: true,
        found: false
    },
    {
        id: 3,
        name: "Anita",
        image: "images/characters/anita.png",
        male: false,
        female: true,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: true,
        glasses: false,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: false,
        blueEyes: true,
        found: false
    },
    {
        id: 4,
        name: "Anne",
        image: "images/characters/anne.png",
        male: false,
        female: true,
        blackHair: true, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 5,
        name: "Bernard",
        image: "images/characters/bernard.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: true,
        blondHair: false,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: true,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 6,
        name: "Bill",
        image: "images/characters/bill.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: true,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: true,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 7,
        name: "Charles",
        image: "images/characters/charles.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: true,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: true,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 8,
        name: "Claire",
        image: "images/characters/claire.png",
        male: false,
        female: true,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: true,
        whiteHair: false,
        glasses: true,
        hat: true,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 9,
        name: "David",
        image: "images/characters/david.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: true,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: true,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 10,
        name: "Eric",
        image: "images/characters/eric.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: true,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: true,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 11,
        name: "Frans",
        image: "images/characters/frans.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: true,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 12,
        name: "George",
        image: "images/characters/george.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: true,
        glasses: false,
        hat: true,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 13,
        name: "Herman",
        image: "images/characters/herman.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: true,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 14,
        name: "Joe",
        image: "images/characters/joe.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: true,
        gingerHair: false,
        whiteHair: false,
        glasses: true,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 15,
        name: "Maria",
        image: "images/characters/maria.png",
        male: false,
        female: true,
        blackHair: false, 
        brownHair: true,
        blondHair: false,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: true,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 16,
        name: "Max",
        image: "images/characters/max.png",
        male: true,
        female: false,
        blackHair: true, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        eyeColor: "brown",
        mustache: true,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 17,
        name: "Paul",
        image: "images/characters/paul.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: true,
        glasses: true,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 18,
        name: "Peter",
        image: "images/characters/peter.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: true,
        glasses: false,
        eyeColor: "blue",
        mustache: false,
        beard: false,
        brownEyes: false,
        blueEyes: true,
        found: false
    },
    {
        id: 19,
        name: "Philip",
        image: "images/characters/phillip.png",
        male: true,
        female: false,
        blackHair: true, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: true,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 20,
        name: "Richard",
        image: "images/characters/richard.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: true,
        blondHair: false,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: true,
        beard: true,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 21,
        name: "Robert",
        image: "images/characters/robert.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: true,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: false,
        blueEyes: true,
        found: false
    },
    {
        id: 22,
        name: "Sam",
        image: "images/characters/sam.png",
        male: true,
        female: false,
        blackHair: false, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: true,
        glasses: true,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 23,
        name: "Susan",
        image: "images/characters/susan.png",
        male: false,
        female: true,
        blackHair: false, 
        brownHair: false,
        blondHair: true,
        gingerHair: false,
        whiteHair: false,
        glasses: false,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: true,
        blueEyes: false,
        found: false
    },
    {
        id: 24,
        name: "Tom",
        image: "images/characters/tom.png",
        male: true,
        female: false,
        blackHair: true, 
        brownHair: false,
        blondHair: false,
        gingerHair: false,
        whiteHair: false,
        glasses: true,
        hat: false,
        mustache: false,
        beard: false,
        brownEyes: false,
        blueEyes: true,
        found: false
    }
]